version: "3.8"

services:
    gateway:
      image: 532336587024.dkr.ecr.us-east-1.amazonaws.com/gateway-server:1.0.0
      networks:
        - maika-net
      ports:
        - "8081:8081"
      deploy:
        replicas: 1
        update_config:
          parallelism: 1
          delay: 10s
        resources:
          limits:
            cpus: '0.30'
            memory: 512M
          reservations:
            cpus: '0.10'
            memory: 128M
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      env_file:
        - ./.env
      volumes:
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      depends_on:
        - configuration
        - discovery